//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pApp_Serv_WEB.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursosVacacionales : Base
    {
        public string Documento { get; set; }
        public string NombreDocente { get; set; }
        public int CantidadCursos { get; set; }
        public float PorcentajeDescuento { get; set; }
        public int ValorPagoAntesDcto { get; set; }
        public int ValorDescuento { get; set; }
        public int TotalPagar { get; set; }
    }
}
